version: v1.0

fail_fast: true

plan: pro

paths:
  - "**/*.go"
  - "**/go.mod"
  - "**/go.sum"
  - .neetoci/**

machine_type: multi

commands:
  - checkout
  - neetoci-version go 1.26
  - go mod download
  - gofmt -l . | tee /tmp/fmt_output && test ! -s /tmp/fmt_output
  - go vet ./...
  - go test ./...

triggers:
  - event: branch
    branch_name: main
  - event: pull_request
