version: v1.0

fail_fast: true

plan: pro

paths:
  - app/**
  - bin/**
  - config/**
  - db/**
  - lib/**
  - test/**
  - .neetoci/default.yml
  - .neetoci/scripts/run_eslint_on_modified_files.sh
  - .neetoci/scripts/run_rubocop_and_erblint_on_modified_files.sh
  - .neetoci/scripts/check_schema_drift.sh
  - Gemfile*
  - package.json
  - yarn.lock
  - Rakefile
  - .env.test
  - config.ru
  - .*.yml
  - .ruby-version
  - .node-version
  - .nvmrc
  - .active_record_doctor.rb
  - .prettierrc.js
  - "*.config.*"

machine_type: multi

commands:
  - checkout
  - neetoci-version go 1.26
  - go mod download
  - gofmt -l . | tee /tmp/fmt_output && test ! -s /tmp/fmt_output
  - go vet ./...
  - go test ./...

triggers:
  - event: branch
    branch_name: main
  - event: pull_request
