version: v1.0

fail_fast: true

plan: pro

machine_type: multi

commands:
  - checkout
  - neetoci-version go 1.26
  - 'curl -fsSL -H "Authorization: token ${GITHUB_TOKEN}" https://raw.githubusercontent.com/neetozone/neeto-cli-commons/v1.0.4/assets/release.sh -o /tmp/neeto-cli-release.sh'
  - echo "72911f510d3ad4f45d2e5353a96caba5e134d4b7c61800417fcca4feb40f1a00  /tmp/neeto-cli-release.sh" | sha256sum -c -
  - bash /tmp/neeto-cli-release.sh

triggers:
  - event: branch
    branch_name: main
